title: KnowsHub's Homepage
page-top-title: KnowsHub&ensp;|&ensp;知拾工坊
top-section-bg-text: KnowsHub&ensp;|&ensp;知拾工坊
home-subtitle: ZKT&ensp;|&ensp;厂长
copyright-text: '&copy; ZKT 2023-2024. All Rights Reserved.'
